ProjetoR/Controllers/RestauranteController.cs
using ProjetoR.Models.ProjetoR;
using ProjetoR.Models.Seguranca;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Timers;
using System.Web;
using System.Web.Mvc;

namespace ProjetoR.Controllers
{
    public class RestauranteController : Controller
    {
        public static Menu MenuAtivo = new Menu("Menu Completo");
        // GET: Restaurante
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Menu()
        {
            return View();
        }

        #region Usuario Login
        public ActionResult Sair()
        {
            Usuario.TornarUsuario(Usuario.CarregarUsuario(Request));
            return RedirectToAction("Index");
        }
        public ActionResult TornarGerente()
        {
            Usuario.Gerente.TornarGerente(Usuario.CarregarUsuario(Request));
            return RedirectToAction("Index");
        }
        public ActionResult TornarCozinha()
        {
            Usuario.Cozinha.TornarCozinha(Usuario.CarregarUsuario(Request));
            return RedirectToAction("Index");
        }
        public ActionResult TornarCliente()
        {
            Mesa mesa = Mesa.CarregarMesa(1);
            Usuario.Cliente.TornarCliente(Usuario.CarregarUsuario(Request),
                Cliente.CriarCliente(mesa.Id));
            mesa.AtualizarOcupacao(true);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

ProjetoR/Controllers/RestauranteGerenteController.cs
using ProjetoR.Models.ProjetoR;
using ProjetoR.Models.Seguranca;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoR.Controllers
{
    public class RestauranteGerenteController : Controller
    {
        #region Gerenciador
        public ActionResult Gerenciador()
        {
            if (Usuario.CarregarUsuario(Request) is Usuario.Gerente)
                return View();
            else
                return RedirectToAction("Index","Restaurante");
        }

        private ActionResult GerenciadorLink()
        {
            return RedirectToAction("Gerenciador");
        }

        [HttpPost]
        public ActionResult AdicionarCategoria(string Nome,string Descricao,string Imediato = null)
        {
            bool _imediato = Imediato==null? false : true;

            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("INSERT INTO Categoria VALUES (@nome,@descricao,@imediato)", conn);
                SqlParameter pNome = new SqlParameter("@nome", Nome);
                SqlParameter pDescricao = new SqlParameter("@descricao", Descricao);
                SqlParameter pImediato = new SqlParameter("@imediato", _imediato);
                comm.Parameters.Add(pNome);
                comm.Parameters.Add(pDescricao);
                comm.Parameters.Add(pImediato);
                conn.Open();
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return GerenciadorLink();
        }
        public ActionResult RemoverCategoria(int id)
        {
            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("DELETE FROM Categoria WHERE Id = @id", conn);
                SqlParameter pId = new SqlParameter("@id", id);
                comm.Parameters.Add(pId);
                conn.Open();
                comm.ExecuteNonQuery();

                comm.CommandText = "DELETE FROM Produto WHERE Categoria = @id";
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return GerenciadorLink();
        }

        [HttpPost]
        public ActionResult AdicionarProduto(string nome,string descricao,string categoria,string preco) 
        {
            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("INSERT INTO Produto VALUES (@nome,@descricao,@categoria,@preco)", conn);
                SqlParameter pNome = new SqlParameter("@nome", nome);
                SqlParameter pDescricao = new SqlParameter("@descricao", descricao);
                SqlParameter pCategoria = new SqlParameter("@categoria", int.Parse(categoria));
                SqlParameter pPreco = new SqlParameter("@preco", decimal.Parse(preco));
                comm.Parameters.Add(pNome);
                comm.Parameters.Add(pDescricao);
                comm.Parameters.Add(pCategoria);
                comm.Parameters.Add(pPreco);
                conn.Open();
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return GerenciadorLink();
        }
        public ActionResult RemoverProduto(int id)
        {
            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("DELETE FROM Produto WHERE Id = @id", conn);
                SqlParameter pId = new SqlParameter("@id", id);
                comm.Parameters.Add(pId);
                conn.Open();
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return GerenciadorLink();
        }
        #endregion


        #region Menu
        public ActionResult MenuLink()
        {
            return RedirectToAction("Menu", "Restaurante");
        }
        public ActionResult MenuRemoverProduto(string id)
        {
            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("DELETE FROM MenuItem WHERE ProdutoId = @id", conn);
                SqlParameter pId = new SqlParameter("@id", int.Parse(id));
                comm.Parameters.Add(pId);
                conn.Open();
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return MenuLink();

        }
        [HttpPost]
        public ActionResult MenuAdicionarProduto(string id)
        {
            SqlConnection conn = new SqlConnection(BancoDeDados.ConnString);
            try
            {
                SqlCommand comm = new SqlCommand("INSERT INTO MenuItem Values(@menuNome,@produtoId)", conn);
                SqlParameter pProdutoId = new SqlParameter("@produtoId",int.Parse(id));
                SqlParameter pMenuNome = new SqlParameter("@menuNome", RestauranteController.MenuAtivo.Nome);
                comm.Parameters.Add(pProdutoId);
                comm.Parameters.Add(pMenuNome);
                conn.Open();
                comm.ExecuteNonQuery();
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

            return MenuLink();
        }
        #endregion
    }
}

ProjetoR/Views/Shared/_Layout.cshtml
@using ProjetoR.Models.Seguranca;
@{ 
    Usuario usuario = Usuario.CarregarUsuario(Request);
}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ProjetoR", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Menu", "Menu", "Restaurante")</li>
                    @if (usuario is Usuario.Gerente)
                    {
                        <li>@Html.ActionLink("Gerenciador", "Gerenciador", "RestauranteGerente") </li>
                    }
                    @if (usuario is Usuario.Cozinha)
                    {
                        <li>@Html.ActionLink("Cozinha", "Index", "RestauranteCozinha") </li>
                    }
                    @if (usuario is Usuario.Cliente)
                    {
                        <li>@Html.ActionLink("Carrinho", "Carrinho", "RestauranteCliente")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>